# Generated by Django 2.2.7 on 2019-11-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
    ]
