# Generated by Django 2.2.7 on 2019-11-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191120_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='logn_link',
            new_name='long_link',
        ),
    ]
